var/www/blueprints/hunters.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

"""
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
"""

import os
import sys
import json

from flask import render_template, jsonify, request, Blueprint, redirect, url_for, Response, abort
from flask_login import login_required, current_user

sys.path.append('modules')
import Flask_config

# Import Role_Manager
from Role_Manager import login_admin, login_org_admin, login_user, login_user_no_api, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from lib import ail_core
from lib.objects import ail_objects
from lib import chats_viewer
from lib import item_basic
from lib import Tracker
from lib import Tag
from packages import Date


bootstrap_label = Flask_config.bootstrap_label

# ============ BLUEPRINT ============
hunters = Blueprint('hunters', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/hunter'))

# ============ VARIABLES ============


# ============ FUNCTIONS ============
def api_validator(api_response):
    if api_response:
        return Response(json.dumps(api_response[0], indent=2, sort_keys=True), mimetype='application/json'), api_response[1]

def create_json_response(data, status_code):
    if status_code == 403:
        abort(403)
    elif status_code == 404:
        abort(404)
    return Response(json.dumps(data, indent=2, sort_keys=True), mimetype='application/json'), status_code

# ============= ROUTES ==============

@hunters.route("/yara/rule/default/content", methods=['GET'])
@login_required
@login_read_only
def get_default_yara_rule_content():
    default_yara_rule = request.args.get('rule')
    res = Tracker.api_get_default_rule_content(default_yara_rule)
    return Response(json.dumps(res[0], indent=2, sort_keys=True), mimetype='application/json'), res[1]

##################
#    TRACKERS    #
##################

@hunters.route('/trackers', methods=['GET'])
@login_required
@login_read_only
def trackers_dashboard():
    user_org = current_user.get_org()
    user_id = current_user.get_user_id()
    trackers = Tracker.get_trackers_dashboard(user_org, user_id)
    for t in trackers:
        t['obj'] = ail_objects.get_obj_basic_meta(ail_objects.get_obj_from_global_id(t['obj']))
    stats = Tracker.get_trackers_stats(user_org, user_id)
    return render_template("trackers_dashboard.html", trackers=trackers, stats=stats, bootstrap_label=bootstrap_label)

@hunters.route("/trackers/all")
@login_required
@login_read_only
def tracked_menu():
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org())
    user_trackers = Tracker.get_user_trackers_meta(user_id)
    global_trackers = Tracker.get_global_trackers_meta()
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers, bootstrap_label=bootstrap_label)

@hunters.route("/trackers/word")
@login_required
@login_read_only
def tracked_menu_word():
    tracker_type = 'word'
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org(), tracker_type='word')
    user_trackers = Tracker.get_user_trackers_meta(user_id, tracker_type='word')
    global_trackers = Tracker.get_global_trackers_meta(tracker_type='word')
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers, bootstrap_label=bootstrap_label, tracker_type=tracker_type)

@hunters.route("/trackers/set")
@login_required
@login_read_only
def tracked_menu_set():
    tracker_type = 'set'
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org(), tracker_type=tracker_type)
    user_trackers = Tracker.get_user_trackers_meta(user_id, tracker_type=tracker_type)
    global_trackers = Tracker.get_global_trackers_meta(tracker_type=tracker_type)
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers, bootstrap_label=bootstrap_label, tracker_type=tracker_type)

@hunters.route("/trackers/regex")
@login_required
@login_read_only
def tracked_menu_regex():
    tracker_type = 'regex'
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org(), tracker_type=tracker_type)
    user_trackers = Tracker.get_user_trackers_meta(user_id, tracker_type=tracker_type)
    global_trackers = Tracker.get_global_trackers_meta(tracker_type=tracker_type)
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers, bootstrap_label=bootstrap_label, tracker_type=tracker_type)

@hunters.route("/trackers/yara")
@login_required
@login_read_only
def tracked_menu_yara():
    tracker_type = 'yara'
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org(), tracker_type=tracker_type)
    user_trackers = Tracker.get_user_trackers_meta(user_id, tracker_type=tracker_type)
    global_trackers = Tracker.get_global_trackers_meta(tracker_type=tracker_type)
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers, bootstrap_label=bootstrap_label, tracker_type=tracker_type)

@hunters.route("/trackers/typosquatting")
@login_required
@login_read_only
def tracked_menu_typosquatting():
    tracker_type = 'typosquatting'
    user_id = current_user.get_user_id()
    org_trackers = Tracker.get_org_trackers_meta(current_user.get_org(), tracker_type=tracker_type)
    user_trackers = Tracker.get_user_trackers_meta(user_id, tracker_type=tracker_type)
    global_trackers = Tracker.get_global_trackers_meta(tracker_type=tracker_type)
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=global_trackers,
                           bootstrap_label=bootstrap_label, tracker_type=tracker_type)

@hunters.route("/trackers/admin")
@login_required
@login_admin
def tracked_menu_admin():
    user_id = current_user.get_user_id()
    user_org = current_user.get_org()
    org_trackers = Tracker.get_orgs_trackers_meta(user_org)
    user_trackers = Tracker.get_users_trackers_meta(user_id)
    return render_template("trackersManagement.html", user_trackers=user_trackers, org_trackers=org_trackers, global_trackers=[],
                           bootstrap_label=bootstrap_label)


@hunters.route("/tracker/show", methods=['GET', 'POST'])
@login_required
@login_read_only
def show_tracker():
    user_id = current_user.get_user_id()
    user_org = current_user.get_org()
    user_role = current_user.get_role()
    filter_obj_types = []

    if request.method == 'POST':
        tracker_uuid = request.form.get('tracker_uuid', None)
        date_from = request.form.get('date_from')
        date_to = request.form.get('date_to')
        for obj_type in Tracker.get_objects_tracked():
            new_filter = request.form.get(f'{obj_type}_obj')
            if new_filter:
                filter_obj_types.append(obj_type)
        filter_obj_types = ail_core.sanitize_tracked_objects(filter_obj_types)
        if len(filter_obj_types) == ail_core.get_nb_objects_tracked():
            filter_obj_types = []
        filter_obj_types = ','.join(filter_obj_types)
        if filter_obj_types:
            return redirect(url_for('hunters.show_tracker', uuid=tracker_uuid, date_from=date_from, date_to=date_to, filter=filter_obj_types))
        else:
            return redirect(url_for('hunters.show_tracker', uuid=tracker_uuid, date_from=date_from, date_to=date_to))

    tracker_uuid = request.args.get('uuid', None)
    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')
    filter_obj_types = ail_core.sanitize_tracked_objects(request.args.get('filter', '').split(','))
    if len(filter_obj_types) == ail_core.get_nb_objects_tracked():
        filter_obj_types = []

    res = Tracker.api_check_tracker_acl(tracker_uuid, user_org, user_id, user_role, 'view')
    if res:  # invalid access
        return Response(json.dumps(res[0], indent=2, sort_keys=True), mimetype='application/json'), res[1]

    if date_from:
        date_from = date_from.replace('-', '')
    if date_to:
        date_to = date_to.replace('-', '')

    tracker = Tracker.Tracker(tracker_uuid)
    meta = tracker.get_meta(options={'description', 'level', 'mails', 'org', 'org_name', 'filters', 'sparkline', 'tags',
                                     'filter_duplicate_notification',
                                     'user', 'webhooks', 'nb_objs', 'objs_stats', 'years'})

    if meta['type'] == 'yara':
        yara_rule_content = Tracker.get_yara_rule_content(meta['tracked'])
    else:
        yara_rule_content = None

    if meta['type'] == 'typosquatting':
        typo_squatting = Tracker.get_tracked_typosquatting_domains(meta['tracked'])
        sorted(typo_squatting)
    else:
        typo_squatting = set()

    if date_from:
        date_from, date_to = Date.sanitise_daterange(date_from, date_to)
        objs = tracker.get_objs_by_daterange(date_from, date_to, filter_obj_types)
        meta['objs'] = []
        options = {'last_full_date', 'pdf'}
        for obj_gid in objs:
            obj_type, obj_subtype, obj_id = obj_gid.split(':', 2)
            obj_meta = ail_objects.get_object_meta(obj_type, obj_subtype, obj_id, options=options, flask_context=True)
            obj_meta['tracker_status'] = tracker.get_obj_status(obj_gid)
            obj_meta['gid'] = obj_gid
            meta['objs'].append(obj_meta)
    else:
        date_from = ''
        date_to = ''
        meta['objs'] = []

    meta['date_from'] = date_from
    meta['date_to'] = date_to

var/www/templates/hunter/menu_sidebar.html
      <div class="col-12 col-lg-2 p-0 bg-light border-right" id="side_menu">

      	<button type="button" class="btn btn-outline-secondary mt-1 ml-3" onclick="toggle_sidebar()">
          <i class="fas fa-align-left"></i>
      	  <span>Toggle Sidebar</span>
      	</button>

      	<nav class="navbar navbar-expand navbar-light bg-light flex-md-column flex-row align-items-start py-2" id="nav_menu">
      		<h5 class="d-flex text-muted w-100" id="nav_title_trackers">
      		  <span>Trackers </span>
      			<a class="ml-auto" href="{{url_for('hunters.add_tracked_menu')}}">
      				<i class="fas fa-plus-circle fa-fw ml-auto"></i>
      			</a>
      		</h5>
      	  <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100"> <!--nav-pills-->
            <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu')}}" id="nav_tracker_">
                <i class="fas fa-ruler-combined fa-fw"></i>
      	        <span>All Trackers</span>
      	      </a>
      	    </li>
      	    <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu_word')}}" id="nav_tracker_word">
                <i class="fas fa-font fa-fw"></i>
      	        <span>Words</span>
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu_set')}}" id="nav_tracker_set">
      	        <i class="fas fa-layer-group fa-fw"></i>
      	        <span>Set</span>
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu_regex')}}" id="nav_tracker_regex">
      	        <i class="fas fa-drafting-compass fa-fw"></i>
                <span>Regex</span>
      	      </a>
      	    </li>
            <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu_yara')}}" id="nav_tracker_yara">
                <span class="bg-danger text-white font-weight-bold" style="font-size: 120%">&nbsp;{ </span>
                <span>&nbsp;YARA</span>
      	      </a>
      	    </li>
			<li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.tracked_menu_typosquatting')}}" id="nav_tracker_typosquatting">
                <i class="fa fa-clone fa-fw"></i>
                <span>Typo-squatting</span>
      	      </a>
      	    </li>
          </ul>
          <h5 class="d-flex text-muted w-100" id="nav_title_retro_hunt">
      		  <span>Retro Hunt </span>
      			<a class="ml-auto" href="{{url_for('hunters.retro_hunt_add_task')}}">
      				<i class="fas fa-plus-circle fa-fw ml-auto"></i>
      			</a>
      		</h5>
      	  <ul class="nav flex-md-column flex-row navbar-nav justify-content-between w-100"> <!--nav-pills-->
            <li class="nav-item">
      	      <a class="nav-link" href="{{url_for('hunters.retro_hunt_all_tasks')}}" id="nav_retro_hunts">
                <i class="fas fa-meteor fa-fw"></i>
      	        <span>Retro Hunt</span>
      	      </a>
      	    </li>
          </ul>
      	</nav>
      </div>

var/www/templates/hunter/trackers_dashboard.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Trackers - AIL</title>
    <link rel="icon" href="{{ url_for('static', filename='image/ail-icon.png') }}">

    <!-- Core CSS -->
    <link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">

    <script src="{{ url_for('static', filename='js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='js/helper.js')}}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap4.min.js') }}"></script>
{#    <script src="{{ url_for('static', filename='js/d3.min.js') }}"></script>#}
{#    <script src="{{ url_for('static', filename='js/d3/sparklines.js') }}"></script>#}

</head>
<body>

{% include 'nav_bar.html' %}

<div class="container-fluid">
    <div class="row">

        {% include 'hunter/menu_sidebar.html' %}

        <div class="col-12 col-lg-10" id="core_content">

                <div class="d-flex justify-content-around my-2">
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu') }}">
                        <div class="card-body">
                            <h5 class="card-title"><i class="fas fa-ruler-combined"></i>
                                All Trackers&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge badge-light">{{ stats['all'] }}</span>
                            </h5>
                        </div>
                    </a>
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu_word') }}">
                        <div class="card-body">
                            <h5 class="card-title"><i class="fas fa-font"></i>
                                Words&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge badge-light">{{ stats['word'] }}</span>
                            </h5>
                        </div>
                    </a>
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu_set') }}">
                        <div class="card-body">
                            <h5 class="card-title"><i class="fas fa-layer-group"></i>
                                Set&nbsp;&nbsp;&nbsp;&nbsp;<span class="badge badge-light">{{ stats['set'] }}</span>
                            </h5>
                        </div>
                    </a>
                </div>

                <div class="d-flex justify-content-around my-2">
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu_regex') }}">
                        <div class="card-body">
                            <h5 class="card-title">
                                <i class="fas fa-drafting-compass"></i>
                                Regex&nbsp;&nbsp;&nbsp;&nbsp;
                                <span class="badge badge-light">{{ stats['regex'] }}</span>
                            </h5>
                        </div>
                    </a>
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu_typosquatting') }}">
                        <div class="card-body">
                            <h5 class="card-title">
                                <i class="fa fa-clone"></i>
                                Typo Squatting&nbsp;&nbsp;&nbsp;&nbsp;
                                <span class="badge badge-light">{{ stats['typosquatting'] }}</span>
                            </h5>
                        </div>
                    </a>
                    <a class="btn btn-info  border-secondary" style="width: 20rem;" href="{{ url_for('hunters.tracked_menu_yara') }}">
                        <div class="card-body">
                            <h5 class="card-title">
                                <span class="bg-danger text-white font-weight-bold" style="font-size: 120%">&nbsp;{ </span>
                                Yara&nbsp;&nbsp;&nbsp;&nbsp;
                                <span class="badge badge-light">{{ stats['yara'] }}</span>
                            </h5>
                        </div>
                    </a>
                </div>

        {# TODO Buttons#}

            <a class="btn btn-primary my-2" href="{{ url_for('hunters.add_tracked_menu') }}">
                <i class="fas fa-plus-circle ml-auto"></i>
                Create New Tracker
            </a>

            <div class="card my-3">
                <div class="card-header bg-dark text-white">
                    <h5 class="card-title"><b>Trackers Last Matches</b></h5>
                </div>
                <div class="card-body">

                    <table class="table">
                        <thead>
                            <tr>
                                <th><i class="fa-solid fa-crosshairs"></i></th>
                                <th>tracker</th>
                                <th class="text-center"><i class="fas fa-cube"></i></th>
                                <th>Time</th>
                            </tr>
                        </thead>
                        <tbody id="tracked_objs">
                            {% for tracker in trackers %}
                                <tr>
                                    <td>{{ tracker['type'] }}</td>
                                    <td style="word-break: break-all;">
                                        <a href="{{ url_for('hunters.show_tracker') }}?uuid={{ tracker['uuid'] }}">{% if tracker['description'] %}{{ tracker['description'] }}{% else %}{{ tracker['tracked'] }}{% endif %}</a>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ tracker['obj']['link'] }}" onmouseenter="show_obj_tooltip(this, '{{ tracker['obj']['gid'] }}')" onmouseleave="hide_obj_tooltip(this)">
                                            <svg height="26" width="26" style="pointer-events:none;">
                                            <g class="nodes">
                                                <circle cx="13" cy="13" r="13" fill="{{ tracker['obj']['icon']['color'] }}"></circle>
                                                <text x="13" y="13" text-anchor="middle" dominant-baseline="central" class="{{ tracker['obj']['icon']['style'] }}" font-size="16px">{{ tracker['obj']['icon']['icon'] }}</text>
                                            </g>
                                        </svg>
                                        </a>
                                    </td>
                                    <td>{{ tracker['timestamp'] }}</td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>

                </div>
            </div>


        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#page-Tracker").addClass("active");
        $("#nav_tracker_{{tracker_type}}").addClass("active");

{#        {% for dict_uuid in global_trackers %}#}
{#            sparkline("sparklines_{{ dict_uuid['uuid'] }}", {{ dict_uuid['sparkline'] }}, {height: 40});#}
{#        {% endfor %}#}

    });

    var url_obj_description = "{{ url_for('correlation.get_description') }}?object_id=";

    function toggle_sidebar() {
        if ($('#nav_menu').is(':visible')) {
            $('#nav_menu').hide();
            $('#side_menu').removeClass('border-right')
            $('#side_menu').removeClass('col-lg-2')
            $('#core_content').removeClass('col-lg-10')
        } else {
            $('#nav_menu').show();
            $('#side_menu').addClass('border-right')
            $('#side_menu').addClass('col-lg-2')
            $('#core_content').addClass('col-lg-10')
        }
    }
</script>

</body>
</html>