var/www/blueprints/tags_ui.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import os
import sys

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, abort
from flask_login import login_required

sys.path.append('modules')
import Flask_config

# Import Role_Manager
from Role_Manager import login_admin, login_user_no_api, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from packages import Date
from lib import Tag
from lib.objects import ail_objects

bootstrap_label = Flask_config.bootstrap_label

# ============ BLUEPRINT ============
tags_ui = Blueprint('tags_ui', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/tags'))

# ============ VARIABLES ============



# ============ FUNCTIONS ============


# ============= ROUTES ==============
@tags_ui.route('/tag/taxonomies')
@login_required
@login_read_only
def tags_taxonomies():
    taxonomies = Tag.get_taxonomies_meta()
    return render_template("tags/taxonomies.html", taxonomies=taxonomies)

@tags_ui.route('/tag/taxonomy')
@login_required
@login_read_only
def tags_taxonomy():
    taxonomy_name = request.args.get('taxonomy')
    taxonomy = Tag.get_taxonomy_meta(taxonomy_name, enabled=True, predicates=True, tags=True, enabled_tags=True)
    if not taxonomy:
        abort(404)
    return render_template("tags/taxonomy.html", taxonomy=taxonomy)

@tags_ui.route('/tag/taxonomy/enable')
@login_required
@login_admin
def taxonomy_enable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_enable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/disable')
@login_required
@login_admin
def taxonomy_disable():
    taxonomy = request.args.get('taxonomy')
    res = Tag.api_disable_taxonomy_tags({'taxonomy': taxonomy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/taxonomy/enable_tags')
@login_required
@login_admin
def taxonomy_enable_tags():
    taxonomy = request.args.get('taxonomy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_taxonomy_tag_enabled({'taxonomy': taxonomy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_taxonomy', taxonomy=taxonomy))

@tags_ui.route('/tag/galaxies')
@login_required
@login_read_only
def tags_galaxies():
    galaxies = Tag.get_galaxies_meta()
    return render_template("tags/galaxies.html", galaxies=galaxies)

@tags_ui.route('/tag/galaxy')
@login_required
@login_read_only
def tags_galaxy():
    galaxy_name = request.args.get('galaxy')
    galaxy = Tag.get_cluster_meta(galaxy_name, enabled=True, tags=True)
    if not galaxy:
        abort(404)
    return render_template("tags/galaxy.html", galaxy=galaxy)

@tags_ui.route('/tag/galaxy/tag')
@login_required
@login_read_only
def tags_galaxy_tag():
    galaxy_type = request.args.get('galaxy')
    tag = request.args.get('tag')
    tag_meta = Tag.get_galaxy_tag_meta(galaxy_type, tag)
    if not tag_meta:
        abort(404)
    return render_template("tags/galaxy_tag.html", galaxy=galaxy_type, tag=tag_meta)

@tags_ui.route('/tag/galaxy/enable')
@login_required
@login_admin
def galaxy_enable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_enable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/disable')
@login_required
@login_admin
def galaxy_disable():
    galaxy = request.args.get('galaxy')
    res = Tag.api_disable_galaxy_tags({'galaxy': galaxy})
    if res:
        return jsonify(res[0]), res[1]
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))

@tags_ui.route('/tag/galaxy/enable_tags')
@login_required
@login_admin
def galaxy_enable_tags():
    galaxy = request.args.get('galaxy')
    tags = request.args.getlist('tags')
    res = Tag.api_update_galaxy_tag_enabled({'galaxy': galaxy, 'tags': tags})
    if res:
        return jsonify(res[0]), 1
    else:
        return redirect(url_for('tags_ui.tags_galaxy', galaxy=galaxy))


@tags_ui.route('/tag/enabled')
@login_required
@login_read_only
def get_all_tags_enabled():
    return jsonify(Tag.get_enabled_tags_with_synonyms_ui())

@tags_ui.route('/tag/confirm')
@login_required
@login_user_no_api
def tag_confirm():
    tag = request.args.get('tag')
    obj_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    obj_id = request.args.get('id', '')
    obj = ail_objects.get_object(obj_type, subtype, obj_id)
    if not obj.exists():
        abort(404)
    Tag.confirm_tag(tag, obj)

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(obj.get_link(flask_context=True))

@tags_ui.route('/tag/add_tags')
@login_required
@login_user_no_api
def add_tags():

    tags = request.args.get('tags')
    tagsgalaxies = request.args.get('tagsgalaxies')
    object_type = request.args.get('type')
    object_subtype = request.args.get('subtype')
    object_id = request.args.get('id')

    list_tag = tags.split(',')
    list_tag_galaxies = tagsgalaxies.split(',')

    res = Tag.api_add_obj_tags(tags=list_tag, galaxy_tags=list_tag_galaxies,
                               object_id=object_id, object_type=object_type, object_subtype=object_subtype)
    # error
    if res[1] != 200:
        return str(res[0])

    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, object_subtype, object_id, flask_context=True))

@tags_ui.route('/tag/delete_tag') # TODO FIX REQUEST PARAMETER
@login_required
@login_user_no_api
def delete_tag():
    object_type = request.args.get('type')
    subtype = request.args.get('subtype', '')
    object_id = request.args.get('id')
    tag = request.args.get('tag')

    res = Tag.api_delete_obj_tags(tags=[tag], object_id=object_id, object_type=object_type, subtype=subtype)
    if res[1] != 200:
        return str(res[0])
    if request.referrer:
        return redirect(request.referrer)
    else:
        return redirect(ail_objects.get_object_link(object_type, subtype, object_id, flask_context=True))


@tags_ui.route('/tag/get_all_tags')
@login_required
@login_read_only
def get_all_tags():
    return jsonify(Tag.get_all_tags())

@tags_ui.route('/tag/get_taxonomies_customs_tags')
@login_required
@login_read_only
def get_all_taxonomies_customs_tags():
    return jsonify(Tag.get_taxonomies_customs_tags(r_list=True))

@tags_ui.route('/tag/get_all_obj_tags')
@login_required
@login_read_only
def get_all_obj_tags():
    object_type = request.args.get('object_type')
    res = ail_objects.api_sanitize_object_type(object_type)
    if res:
        return jsonify(res[0]), res[1]
    return jsonify(Tag.get_all_obj_tags(object_type))

@tags_ui.route('/tag/taxonomies/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomies_tags_enabled_json():
    return jsonify(Tag.get_taxonomies_enabled_tags(r_list=True))

@tags_ui.route('/tag/galaxies/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxies_tags_enabled_json():
    tags = Tag.get_galaxies_enabled_tags()
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/custum/tags/enabled/json')
@login_required
@login_read_only
def tag_custum_tags_enabled_json():
    return jsonify(Tag.get_custom_enabled_tags(r_list=True))

@tags_ui.route('/tag/taxonomie/tags/enabled/json')
@login_required
@login_read_only
def tag_taxonomie_tags_enabled_json():
    taxonomie = request.args.get('taxonomie')
    return jsonify(Tag.get_taxonomie_enabled_tags(taxonomie, r_list=True))

@tags_ui.route('/tag/galaxy/tags/enabled/json')
@login_required
@login_read_only
def tag_galaxy_tags_enabled_json():
    galaxy = request.args.get('galaxy')
    tags = Tag.get_galaxy_enabled_tags(galaxy, r_list=True)
    return jsonify(Tag.get_tags_selector_dict(tags))

@tags_ui.route('/tag/search/item')
@login_required
@login_read_only
def tags_search_items():
    object_type = 'item'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/message')
@login_required
@login_read_only
def tags_search_messages():
    object_type = 'message'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    dict_tagged['date'] = Date.sanitise_date_range('', '', separator='-')
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/image')
@login_required
@login_read_only
def tags_search_images():
    object_type = 'image'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/ocr')
@login_required
@login_read_only
def tags_search_ocrs():
    object_type = 'ocr'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}
    return render_template("tags/search_obj_by_tags.html", bootstrap_label=bootstrap_label, dict_tagged=dict_tagged)

@tags_ui.route('/tag/search/qrcode')
@login_required
@login_read_only
def tags_search_qrcodes():
    object_type = 'qrcode'
    dict_tagged = {"object_type": object_type, "object_name": object_type.title() + "s"}

var/www/templates/modals/add_tags.html
<div id="add_tags_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="add_tags_modal_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Add New Tags</h4>
      </div>

      <div class="modal-body">

        <div class="input-group" >
          <input id="ltags_add_modal" type="text" class="form-control" autocomplete="off" style="width: 760px">
        </div>

        <div class="dropdown">
          <button type="button" class="btn btn-info dropdown-toggle mt-1 mb-3" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-taxonomie-add-modal">
             Taxonomie Selected
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-taxonomie-add-modal"> <!-- TODO: make dropdown-scrollable -->
            <h6 class="dropdown-header">Taxonomie Tags</h6>
            <button class="dropdown-item" type="button" id="add-modal-all-tags-taxonomies">All Tags <i class="fas fa-tags"></i></button>
            <div class="dropdown-divider"></div>
            {% for taxo in modal_add_tags['active_taxonomies'] %}
                <button class="dropdown-item" type="button" id="add-modal-{{ taxo }}-id{{ loop.index0 }}">{{ taxo }}</button>
            {% endfor %}
          </div>
        </div>

        <div class="input-group">
          <input id="ltagsgalaxies_add_modal" type="text" class="form-control" autocomplete="off" style="width: 760px">
        </div>

        <div class="dropdown">
          <button type="button" class="btn btn-info dropdown-toggle mt-1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" id="dropdown-galaxy-add-modal">
             Galaxy Selected
          </button>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="dropdown-galaxy-add-modal"> <!-- TODO: make dropdown-scrollable -->
            <h6 class="dropdown-header">Galaxy Tags</h6>
            <button class="dropdown-item" type="button" id="add-modal-all-tags-galaxies">All Tags <i class="fas fa-tags"></i></button>
            <div class="dropdown-divider"></div>
            {% for galaxy in modal_add_tags['active_galaxies'] %}
                <button class="dropdown-item" type="button" id="add-modal-{{ galaxy }}-idgalax{{ loop.index0 }}">{{ galaxy }}</button>
            {% endfor %}
          </div>
        </div>

      </div>

      <div class="modal-footer">
        <a class="btn btn-link" href="{{ url_for('tags_ui.tags_taxonomies') }}" target="_blank">
            <span class="label-icon">Taxonomies</span>
            <i class="fas fa-wrench fa-2x"></i>
        </a>
        <a class="btn btn-link" href="{{ url_for('tags_ui.tags_galaxies') }}" target="_blank">
            <span class="label-icon">Galaxies</span>
            <i class="fas fa-rocket fa-2x"></i>
        </a>
        <button class="btn btn-primary" onclick="addTags()">
            <i class="fas fa-plus"></i>
            Add Tags
        </button>
        <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>

      </div>
    </div>
  </div>
</div>

<script> // TODO: add tags to PASTE or DOMAIN
var ltags_modal_add;
var ltagsgalaxies_modal_add;

$.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
    function(data) {

      ltags_modal_add = $('#ltags_add_modal').tagSuggest({
        data: data,
        maxDropHeight: 200,
        name: 'ltags_modal_add'
      });
    });

$.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
  function(data) {

    ltagsgalaxies_modal_add = $('#ltagsgalaxies_add_modal').tagSuggest({
      data: data,
      maxDropHeight: 200,
      name: 'ltagsgalaxies_modal_add'
    });
  });

jQuery("#add-modal-all-tags-taxonomies").click(function(e){
        //change input tags list
      $.getJSON("{{ url_for('tags_ui.get_all_taxonomies_customs_tags') }}",
        function(data) {
          ltags_modal_add.setData(data)
      });
    });

jQuery("#add-modal-all-tags-galaxies").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxies_tags_enabled_json') }}",
        function(data) {
          ltagsgalaxies_modal_add.setData(data)
      });
    });

{% for taxo in modal_add_tags['active_taxonomies'] %}
    jQuery("#add-modal-{{ taxo }}-id{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_taxonomie_tags_enabled_json') }}?taxonomie={{ taxo }}",
        function(data) {
          ltags_modal_add.setData(data)
  });
});
{% endfor %}

{% for galaxy in modal_add_tags['active_galaxies'] %}
    jQuery("#add-modal-{{ galaxy }}-idgalax{{ loop.index0 }}").click(function(e){
      $.getJSON("{{ url_for('tags_ui.tag_galaxy_tags_enabled_json') }}?galaxy={{ galaxy }}",
        function(data) {
          ltagsgalaxies_modal_add.setData(data)
  });
});
{% endfor %}

function addTags() {
  var tags = ltags_modal_add.getValue()
  var tagsgalaxy = ltagsgalaxies_modal_add.getValue()
  window.location.replace("{{ url_for('tags_ui.add_tags') }}?tags=" + tags + "&tagsgalaxies=" + tagsgalaxy + "&type={{ modal_add_tags['object_type'] }}&subtype={{ modal_add_tags['object_subtype'] }}&id={{ modal_add_tags['object_id'] }}");
}
</script>

var/www/templates/modals/create_hive_case.html
<div id="create_hive_case_modal" class="modal fade" role="dialog">
    <div class="modal-dialog modal-lg">

        <div id="create_hive_case_modal_content" class="modal-content">
            <div class="modal-header justify-content-center">
                <img id="hive-logo" src="{{url_for('static', filename='image/thehive-logo.png') }}" width="500" >
            </div>

            <form method="post" action="{{ url_for('import_export.create_thehive_case') }}" target="_blank">

                <div class="modal-body">

                    <div class="input clear required">
                        <label for="EventThreatLevelId">Threat Level</label>
                        <select name="threat_level_hive" id="EventThreatLevelId" required="required">
                            <option value="1">High</option>
                            <option value="2" selected="selected">Medium</option>
                            <option value="3">Low</option>
                        </select>
                    </div>
                    <div class="input select required">
                        <label for="hive_tlp">TLP</label>
                        <select name="hive_tlp" id="hive_tlp" required="required" class="selectpicker">
                            <option value="0">White</option>
                            <option value="1">Green</option>
                            <option value="2" selected="selected">Amber</option>
                            <option value="3">Red</option>
                        </select>
                    </div>
                    <div class="clear">
                        <label for="hive_case_title">Title</label>
                        <input name="hive_case_title" class="form-control span6" placeholder="Title" type="text" id="hive_case_title"/>
                    </div>
                    <div class="clear">
                        <label for="hive_description">Description</label>
                        <input name="hive_description" class="form-control span6" placeholder="Quick Case Description" type="text" id="hive_description"/>
                    </div>
                    <input type="hidden" id="obj_type" name="obj_type" value="item">
                    <input type="hidden" id="obj_id" name="obj_id" value="{{ dict_item['id'] }}">
                </div>

            <div class="modal-footer">
                <button class="btn btn-primary" type="submit">
                    <i class="fas fa-plus"></i>
                    Create Case
                </button>

                <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>
            </div>

            </form>

        </div>
    </div>
</div>

var/www/templates/modals/edit_tag.html
<div id="edit_tags_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="add_tags_modal_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Edit Tag</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-center">
        <h2><span class="badge badge-warning" id="modal_tag_edit_tag_id">Warning</span></h2>
      </div>

      <div class="modal-footer">

        <!-- <a href="?object_id=rrrrr&tag=eeeeee&status=tp" class="btn btn-outline-success mr-0" data-toggle="tooltip" title="Good Detection">
          <i class="fas fa-thumbs-up"></i>
        </a>
        <a href="?object_id=rrrrr&tag=eeeeee&status=fp" class="btn btn-outline-danger mr-auto" data-toggle="tooltip" title="Bad Detection">
          <i class="fas fa-thumbs-down"></i>
        </a> -->

        <a href="#" class="btn btn-primary" id="modal_tag_confirm">
          <i class="fas fa-check"></i> Confirm this Tag
        </a>

        <a href="#" class="btn btn-danger" id="modal_tag_edit_delete_tag">
          <i class="fas fa-trash-alt"></i> Delete this Tag
        </a>

      </div>
    </div>
  </div>
</div>

<script>
// tagid + objtype + objid
$('#edit_tags_modal').on('show.bs.modal', function (event) {
    var tag_confirm = $('#modal_tag_confirm');
    tag_confirm.hide();
    var button = $(event.relatedTarget);
    var tagid = button.data('tagid')
    var objtype = button.data('objtype')
    var objsubtype = button.data('objsubtype')
    var objid = button.data('objid')
    var modal = $(this)
    modal.find('#modal_tag_edit_tag_id').text(tagid)
    if (tagid.startsWith("infoleak:automatic-detection")) {
        tag_confirm.show();
        modal.find('#modal_tag_confirm').prop("href", "{{ url_for('tags_ui.tag_confirm') }}?type="+ objtype +"&subtype="+ objsubtype +"&id="+ objid +"&tag="+ tagid);
    }
    modal.find('#modal_tag_edit_delete_tag').prop("href", "{{ url_for('tags_ui.delete_tag') }}?type="+ objtype +"&subtype="+ objsubtype +"&id="+ objid +"&tag="+ tagid);
  })
</script>

var/www/templates/modals/investigations_register_obj.html
<link href="{{ url_for('static', filename='css/tags.css') }}" rel="stylesheet" type="text/css" />
<script src="{{ url_for('static', filename='js/tags.js') }}"></script>

<div id="investigations_register_obj_modal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="investigations_register_obj_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Add to Investigations</h4>
      </div>

      <div class="modal-body">

        <div class="input-group" >
          <input id="linvestigations" type="text" class="form-control" autocomplete="off" style="width: 760px">
        </div>
        <div class="form- mt-2">
            <label for="inv_obj_comment">Object Comment <i>(optional)</i>:</label>
            <textarea class="form-control" id="inv_obj_comment" name="inv_obj_comment" rows="2"></textarea>
        </div>

      </div>

      <div class="modal-footer">
        <a class="btn btn-info" href="{{ url_for('investigations_b.add_investigation') }}" target="_blank">
            <i class="fas fa-microscope"></i>
            <span class="label-icon">Create Investigation </span>
        </a>
        <button class="btn btn-primary" onclick="Register_Obj()">
            <i class="fas fa-plus"></i>
            Add to Investigations
        </button>
        <button type="button" class="btn btn-outline-dark" data-dismiss="modal" >Close</button>

      </div>
    </div>
  </div>
</div>

<script>
var linvestigations;

$('#investigations_register_obj_modal').on('shown.bs.modal', function () {

  $.getJSON("{{ url_for('investigations_b.get_investigations_selector_json') }}",
      function(data) {
        console.log(data);

        linvestigations = $('#linvestigations').tagSuggest({
          data: data,
          maxDropHeight: 200,
          name: 'linvestigations',
          emptyText: 'Select Investigations'
        });
      }
  );

});

function Register_Obj() {
    var uuids = linvestigations.getValue();
    var comment = $('#inv_obj_comment').val();
    // TODO: REQUEST
    var url = "{{ url_for('investigations_b.register_investigation') }}?uuids=" + uuids + "&type={{ obj_type }}&subtype={{ obj_subtype }}&id={{ obj_id }}"
    if (comment) {
        url += "&comment=" + comment;
    }
    window.location.replace(url);
}
</script>

var/www/templates/modals/retro_hunt_remove_object.html
<div id="modal_retro_hunt_remove_object" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="modal_retro_hunt_remove_object_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Remove Object From Retro Hunt</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-center">
        <h2><span class="badge-warning" id="modal_retro_hunt_remove_object_gid">Warning</span></h2>
      </div>

      <div class="modal-footer">

        <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>

        <a href="#" class="btn btn-danger" id="modal_retro_hunt_remove_object_delete">
          <i class="fas fa-trash-alt"></i> Remove
        </a>

      </div>
    </div>
  </div>
</div>

<script>
// tagid + objtype + objid
$('#modal_retro_hunt_remove_object').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget);
    let obj_gid = button.data('obj_gid')
    let retro_uuid = button.data('retro_uuid')
    let modal = $(this)
    modal.find('#modal_retro_hunt_remove_object_gid').text(obj_gid)
    modal.find('#modal_retro_hunt_remove_object_delete').prop("href", "{{ url_for('hunters.retro_hunt_object_remove') }}?uuid="+ retro_uuid +"&gid="+ obj_gid);
  })
</script>

var/www/templates/modals/tracker_remove_object.html
<div id="modal_tracker_remove_object" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <div id="modal_tracker_remove_object_content" class="modal-content">
      <div class="modal-header" style="border-bottom: 4px solid #cccccc; background-color: #cccccc; color: #ffffff;">
        <h4>Remove Object From Tracker</h4>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body text-center">
        <h2><span class="badge-warning" id="modal_tracker_remove_object_gid">Warning</span></h2>
      </div>

      <div class="modal-footer">

        <button type="button" class="btn btn-default" data-dismiss="modal" >Close</button>

        <a href="#" class="btn btn-danger" id="modal_tracker_remove_object_delete">
          <i class="fas fa-trash-alt"></i> Remove
        </a>

      </div>
    </div>
  </div>
</div>

<script>
// tagid + objtype + objid
$('#modal_tracker_remove_object').on('show.bs.modal', function (event) {
    var button = $(event.relatedTarget);
    let obj_gid = button.data('obj_gid')
    let tracker_uuid = button.data('tracker_uuid')
    let modal = $(this)
    modal.find('#modal_tracker_remove_object_gid').text(obj_gid)
    modal.find('#modal_tracker_remove_object_delete').prop("href", "{{ url_for('hunters.tracker_object_remove') }}?uuid="+ tracker_uuid +"&gid="+ obj_gid);
  })
</script>