var/www/blueprints/languages_ui.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

"""
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
"""

import os
import sys
import json

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response, abort
from flask_login import login_required

# Import Role_Manager
from Role_Manager import login_admin, login_user_no_api, login_read_only

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from lib import ail_core
from lib import Language
from lib import Tag
from lib.objects import ail_objects

# ============ BLUEPRINT ============
languages_ui = Blueprint('languages_ui', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/chats_explorer'))

# ============ VARIABLES ============
# bootstrap_label = ['primary', 'success', 'danger', 'warning', 'info']

def create_json_response(data, status_code):
    return Response(json.dumps(data, indent=2, sort_keys=True), mimetype='application/json'), status_code

# ============ FUNCTIONS ============

# ============= ROUTES ==============
@languages_ui.route("/languages/object/translate", methods=['POST'])
@login_required
@login_user_no_api
def translate_object():
    obj_type = request.form.get('type')
    subtype = request.form.get('subtype')
    obj_id = request.form.get('id')
    source = request.form.get('language_target')
    target = request.form.get('target')
    translation = request.form.get('translation')
    if target == "Don't Translate":
        target = None

    resp = ail_objects.api_manually_translate(obj_type, subtype, obj_id, source, target, translation)
    if resp[1] != 200:
        return create_json_response(resp[0], resp[1])
    else:
        if request.referrer:
            return redirect(request.referrer)
        else:
            if obj_type == 'ocr':
                return redirect(url_for('objects_ocr.object_ocr', id=obj_id, target=target))  # TODO change to support all objects

@languages_ui.route("/languages/object/detect/language", methods=['GET'])
@login_required
@login_user_no_api
def detect_object_language():
    obj_type = request.args.get('type')
    subtype = request.args.get('subtype')
    obj_id = request.args.get('id')
    target = request.args.get('target')

    resp = ail_objects.api_detect_language(obj_type, subtype, obj_id)
    if resp[1] != 200:
        return create_json_response(resp[0], resp[1])
    else:
        if request.referrer:
            return redirect(request.referrer)
        else:
            if obj_type == 'ocr':
                return redirect(url_for('objects_ocr.object_ocr', id=obj_id, target=target))  # TODO change to support all objects

var/www/blueprints/objects_ocr.py
#!/usr/bin/env python3
# -*-coding:UTF-8 -*

'''
    Blueprint Flask: crawler splash endpoints: dashboard, onion crawler ...
'''

import json
import os
import sys

from io import BytesIO

from flask import Flask, render_template, jsonify, request, Blueprint, redirect, url_for, Response, abort, send_file, send_from_directory
from flask_login import login_required

# Import Role_Manager
from Role_Manager import login_admin, login_read_only, no_cache

sys.path.append(os.environ['AIL_BIN'])
##################################
# Import Project packages
##################################
from lib import Language
from lib import Tag
from lib.objects import Ocrs

from packages import Date

# ============ BLUEPRINT ============
objects_ocr = Blueprint('objects_ocr', __name__, template_folder=os.path.join(os.environ['AIL_FLASK'], 'templates/objects/ocr'))

# ============ VARIABLES ============
bootstrap_label = ['primary', 'success', 'danger', 'warning', 'info']

def create_json_response(data, status_code):
    return Response(json.dumps(data, indent=2, sort_keys=True), mimetype='application/json'), status_code

# ============ FUNCTIONS ============
@objects_ocr.route('/ocr/<path:filename>')
@login_required
@login_read_only
@no_cache
def ocr_image(filename):
    if not filename:
        abort(404)
    if not 64 <= len(filename) <= 70:
        abort(404)
    filename = filename.replace('/', '')
    ocr = Ocrs.Ocr(filename)
    return send_file(BytesIO(ocr.draw_bounding_boxs()), mimetype='image/png')


@objects_ocr.route("/objects/ocrs", methods=['GET'])
@login_required
@login_read_only
def objects_ocrs():
    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')
    show_objects = request.args.get('show_objects')
    date = Date.sanitise_date_range(date_from, date_to)
    date_from = date['date_from']
    date_to = date['date_to']

    if show_objects:
        dict_objects = Ocrs.Ocrs().api_get_meta_by_daterange(date_from, date_to)
    else:
        dict_objects = {}

    return render_template("OcrDaterange.html", date_from=date_from, date_to=date_to,
                           dict_objects=dict_objects, show_objects=show_objects)


@objects_ocr.route("/objects/ocrs/post", methods=['POST'])
@login_required
@login_read_only
def objects_ocrs_post():
    date_from = request.form.get('date_from')
    date_to = request.form.get('date_to')
    show_objects = request.form.get('show_objects')
    return redirect(url_for('objects_ocr.objects_ocrs', date_from=date_from, date_to=date_to, show_objects=show_objects))


@objects_ocr.route("/objects/ocrs/range/json", methods=['GET'])
@login_required
@login_read_only
def objects_ocrs_range_json():
    date_from = request.args.get('date_from')
    date_to = request.args.get('date_to')
    date = Date.sanitise_date_range(date_from, date_to)
    date_from = date['date_from']
    date_to = date['date_to']
    return jsonify(Ocrs.Ocrs().api_get_chart_nb_by_daterange(date_from, date_to))


@objects_ocr.route("/objects/ocr", methods=['GET'])
@login_required
@login_read_only
def object_ocr():
    obj_id = request.args.get('id')
    target = request.args.get('target')
    if target == "Don't Translate":
        target = None
    meta = Ocrs.api_get_ocr(obj_id, target)
    if meta[1] != 200:
        return create_json_response(meta[0], meta[1])
    else:
        meta = meta[0]
        languages = Language.get_translation_languages()
        return render_template("ShowOcr.html", meta=meta,
                               bootstrap_label=bootstrap_label,
                               ail_tags=Tag.get_modal_add_tags(meta['id'], meta['type'], meta['subtype']),
                               translation_languages=languages, translation_target=target)


# ============= ROUTES ==============

var/www/templates/objects/ocr/ShowOcr.html
<!DOCTYPE html>
<html>

<head>
  <title>OCR - AIL</title>
	<link rel="icon" href="{{ url_for('static', filename='image/ail-icon.png') }}">

  <!-- Core CSS -->
	<link href="{{ url_for('static', filename='css/bootstrap4.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/font-awesome.min.css') }}" rel="stylesheet">
	<link href="{{ url_for('static', filename='css/dataTables.bootstrap.min.css') }}" rel="stylesheet">
    <link href="{{ url_for('static', filename='css/tags.css') }}" rel="stylesheet" type="text/css" />
    <link href="{{ url_for('static', filename='css/ail-project.css') }}" rel="stylesheet">

  <!-- JS -->
	<script src="{{ url_for('static', filename='js/jquery.js')}}"></script>
    <script src="{{ url_for('static', filename='js/popper.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/bootstrap4.min.js') }}"></script>
	<script src="{{ url_for('static', filename='js/jquery.dataTables.min.js')}}"></script>
	<script src="{{ url_for('static', filename='js/dataTables.bootstrap.min.js')}}"></script>
    <script src="{{ url_for('static', filename='js/tags.js') }}"></script>

</head>
<body>

	{% include 'nav_bar.html' %}

	<div class="container-fluid">
		<div class="row">

			{% include 'sidebars/sidebar_objects.html' %}

			<div class="col-12 col-lg-10" id="core_content">

                {% with meta=meta, is_correlation=False %}
                    {% include 'objects/ocr/card_ocr.html' %}
                {% endwith %}


{#                {% if meta['extracted_matches'] %}#}
{#                    <div id="accordion_extracted" class="mb-3 mx-3">#}
{#                        <div class="card">#}
{#                            <div class="card-header py-1" id="heading_extracted">#}
{#                                <div class="row">#}
{#                                    <div class="col-11">#}
{#                                        <div class="mt-2">#}
{#                                            <img id="misp-logo" src="{{ url_for('static', filename='image/ail-icon.png')}}" height="32"> Extracted&nbsp;&nbsp;#}
{#                                            <div class="badge badge-warning">{{meta['extracted_matches']|length}}</div>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                    <div class="col-1">#}
{#                                        <button class="btn btn-link btn-lg py-2 float-right rotate down" data-toggle="collapse" data-target="#collapse_extracted" aria-expanded="true" aria-controls="collapseDecoded">#}
{#                                            <i class="fas fa-chevron-circle-down"></i>#}
{#                                        </button>#}
{#                                    </div>#}
{#                                </div>#}
{#                            </div>#}
{##}
{#                            <div id="collapse_extracted" class="collapse" aria-labelledby="heading_extracted" data-parent="#accordion_extracted">#}
{#                                <div class="card-body">#}
{#                                    <table id="table_extracted" class="table table-striped">#}
{#                                        <thead class="thead-dark">#}
{#                                        <tr>#}
{#                                            <th>Type</th>#}
{#                                            <th>ID</th>#}
{#                                            <th>Extracted</th>#}
{#                                        </tr>#}
{#                                        </thead>#}
{#                                        <tbody>#}
{#                                        {% for match in meta['extracted_matches'] %}#}
{#                                            <tr>#}
{#                                                <td>#}
{#                                                    <svg height="26" width="26">#}
{#                                                        <g class="nodes">#}
{#                                                            <circle cx="13" cy="13" r="13" fill="{{ meta['extracted_matches'][match]['icon']['color'] }}"></circle>#}
{#                                                            <text x="13" y="13" text-anchor="middle" dominant-baseline="central" class="graph_node_icon {{ meta['extracted_matches'][match]['icon']['style'] }}" font-size="16px">{{ meta['extracted_matches'][match]['icon']['icon'] }}</text>#}
{#                                                        </g>#}
{#                                                    </svg>#}
{#                                                    {{ meta['extracted_matches'][match]['subtype'] }}#}
{#                                                </td>#}
{#                                                <td>{{ meta['extracted_matches'][match]['id'] }}</td>#}
{#                                                <td>#}
{#                                                    {% for row in meta['extracted_matches'][match]['matches'] %}#}
{#                                                        <a href="#{{ row[0] }}:{{row[1] }}">{{ row[2] }}</a><br>#}
{#                                                    {% endfor %}#}
{#                                                </td>#}
{#                                            </tr>#}
{#                                        {% endfor %}#}
{#                                        </tbody>#}
{#                                    </table>#}
{#                                </div>#}
{#                            </div>#}
{##}
{#                        </div>#}
{#                    </div>#}
{#                {% endif %}#}


                {% with translate_url=url_for('objects_ocr.object_ocr', id=meta['id']), obj_id=meta['id'] %}
                    {% include 'chats_explorer/block_translation.html' %}
                {% endwith %}
                <div class="mb-4"></div>

            </div>

        </div>
    </div>

<script>
    var chart = {};
    $(document).ready(function(){
        $("#page-Decoded").addClass("active");
        $("#nav_chat").addClass("active");
  });

function toggle_sidebar(){
	if($('#nav_menu').is(':visible')){
		$('#nav_menu').hide();
		$('#side_menu').removeClass('border-right')
		$('#side_menu').removeClass('col-lg-2')
		$('#core_content').removeClass('col-lg-10')
	}else{
		$('#nav_menu').show();
		$('#side_menu').addClass('border-right')
		$('#side_menu').addClass('col-lg-2')
		$('#core_content').addClass('col-lg-10')
	}
}
</script>

</body>

</html>

var/www/templates/objects/ocr/card_ocr.html
<link href="{{ url_for('static', filename='css/tags.css') }}" rel="stylesheet" type="text/css" />
<script src="{{ url_for('static', filename='js/tags.js') }}"></script>

{% with modal_add_tags=ail_tags %}
	{% include 'modals/add_tags.html' %}
{% endwith %}

{% include 'modals/edit_tag.html' %}

<style>
    .object_image {
        filter: blur(5px);
    }
</style>

<div class="card my-1">
	<div class="card-header">
		<h4 class="text-secondary">{{ meta["id"] }} :</h4>
		<ul class="list-group mb-2">
            <li class="list-group-item py-0">
                <table class="table">
                    <tbody style="font-size: 15px;">
                    <tr>
                        <td>
                            <svg height="26" width="26">
                                <g class="nodes">
                                    <circle cx="13" cy="13" r="13" fill="orange"></circle>
                                    <text x="13" y="13" text-anchor="middle" dominant-baseline="central" class="{{ meta["svg_icon"]["style"] }}" font-size="16px">{{ meta["svg_icon"]["icon"] }}</text>
                                </g>
                            </svg>
                            {{ meta['type'] }}
                        </td>
                        <td><b>First Seen:</b> {% if meta['first_seen'] %}{{ meta['first_seen'][0:4] }}-{{ meta['first_seen'][4:6] }}-{{ meta['first_seen'][6:8] }}{% endif %}</td>
                        <td><b>Last Seen:</b> {% if meta['last_seen'] %}{{ meta['last_seen'][0:4] }}-{{ meta['last_seen'][4:6] }}-{{ meta['last_seen'][6:8] }}{% endif %}</td>
                    </tr>
                    </tbody>
                </table>
            </li>
			<li class="list-group-item py-0">
				<div id="accordion_image" class="my-3">
                    <div class="card">
                        <div class="card-header py-1" id="headingImage">
                            <button class="btn w-100 collapsed rotate" data-toggle="collapse" data-target="#collapseImage" aria-expanded="false" aria-controls="collapseImage">
                                <span class="row text-left">
                                    <div class="col-11">
                                        <span class="mt-2">
                                            <i class="far fa-image"></i> Show Image&nbsp;&nbsp;
                                        </span>
                                    </div>
                                    <div class="col-1 text-primary">
                                        <i class="fas fa-chevron-circle-down"></i>
                                    </div>
                                </span>
                            </button>
                        </div>
                        <div id="collapseImage" class="collapse show" aria-labelledby="headingImage" data-parent="#accordion_image">
                            <div class="card-body text-center">
                                {% include 'objects/image/block_blur_img_slider.html' %}

								<img class="object_image mb-1" usemap="#image-map" src="{{ url_for('objects_ocr.ocr_image', filename=meta['id'])}}">
                                <map name="image-map">
                                    {% for c in meta['map'] %}
                                        <area shape="poly" coords="{{ c[0] }}" title="{{ c[1] }}">
                                    {% endfor %}
                                </map>
                            </div>
                        </div>
                    </div>
                </div>
			</li>
            <li class="list-group-item py-0">
                <pre class="my-0" style="white-space: pre-wrap;">{{ meta['content'] }}</pre>
                {% if meta['translation'] %}
                    <hr class="m-1">
                    <pre class="my-0 text-secondary" style="white-space: pre-wrap;">{{ meta['translation'] }}</pre>
               {% endif %}



                {% if not is_correlation %}
                    <div class="my-1">

                        {% set mess_id_escape= meta['id'] | replace("/", "_") %}
                        <span class="btn btn-outline-dark p-0 px-1" type="button" data-toggle="collapse" data-target="#collapseTrans{{ mess_id_escape }}" aria-expanded="false" aria-controls="collapseTrans{{ mess_id_escape }}">
                            <i class="fas fa-language"></i> {% if meta['language'] %}{{ meta['language'] }}{% endif %}
                        </span>
                        <div class="collapse" id="collapseTrans{{ mess_id_escape }}">
                            <div class="card card-body">
                                <form method="post" action="{{ url_for('languages_ui.translate_object') }}">
                                    <input type="text" id="type" name="type" value="{{meta['type']}}" hidden>
                                    <input type="text" id="id" name="id" value="{{meta['id']}}" hidden>
                                    <span class="badge badge-primary">Source:</span>
                                    <span class="">
                                        <select id="language_target" name="language_target" class="form-select" aria-label="Message Language" onchange="$('#translation').val('');">
                                                <option selected value="{{ meta['language'] }}">{{ meta['language'] }}</option>
                                            {% for language in translation_languages %}
                                                <option value="{{ language }}">{{ translation_languages[language] }}</option>
                                            {% endfor %}
                                        </select>
                                    </span>
                                    {% if translation_target %}
                                        <input type="text" id="target" name="target" value="{{translation_target}}" hidden>
                                        &nbsp;&nbsp;&nbsp;&nbsp;<span class="badge badge-primary">Target:</span><span>{{translation_target}}</span>
                                        <textarea class="form-control" id="translation" name="translation">{{ meta['translation'] }}</textarea>
                                        <button class="btn btn-dark" type="submit">
                                            <i class="fas fa-pen-alt"> Update Language or Translation</i>
                                        </button>
                                    {% else %}
                                        <button class="btn btn-dark" type="submit">
                                            <i class="fas fa-pen-alt"> Update Language</i>
                                        </button>
                                    {% endif %}
                                </form>
                                <div>
                                    <a class="btn btn-primary" href="{{ url_for('languages_ui.detect_object_language')}}?type={{ meta['type'] }}&id={{ meta['id'] }}">
                                        <i class="fas fa-redo"></i> Detect Language
                                    </a>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endif %}




            </li>

			<li class="list-group-item py-0">
				<div class="my-2">
					Tags:
					{% for tag in meta['tags'] %}
                        <button class="btn btn-{{ bootstrap_label[loop.index0 % 5] }}"
                                data-toggle="modal" data-target="#edit_tags_modal"
						        data-tagid="{{ tag }}" data-objtype="{{ meta['type'] }}" data-objsubtype="" data-objid="{{ meta["id"] }}">
                                {{ tag }}
						</button>
					{%  endfor %}
					<button type="button" class="btn btn-light" data-toggle="modal" data-target="#add_tags_modal">
                        <i class="far fa-plus-square"></i>
                    </button>
				</div>
			</li>
		</ul>

		{% with obj_type='ocr', obj_id=meta['id'], obj_subtype='' %}
			{% include 'modals/investigations_register_obj.html' %}
		{% endwith %}
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#investigations_register_obj_modal">
			<i class="fas fa-microscope"></i> Investigations
		</button>

        <span class="mb-2 float-right">
            {% if is_correlation %}
                <a href="{{ url_for('objects_ocr.object_ocr')}}?subtype={{ meta['subtype'] }}&id={{ meta['id'] }}">
                    <button class="btn btn-info"><i class="fas fa-expand"></i> Show Object</button>
                </a>
            {% else %}
                <a href="{{ url_for('correlation.show_correlation')}}?type={{ meta['type'] }}&subtype={{ meta['subtype'] }}&id={{ meta['id'] }}">
                    <button class="btn btn-info"><i class="far fa-eye"></i> Correlations &nbsp;
                    </button>
                </a>
            {% endif %}
        </span>

	</div>
</div>

var/www/templates/objects/ocr/card_qrcode.html
<link href="{{ url_for('static', filename='css/tags.css') }}" rel="stylesheet" type="text/css" />
<script src="{{ url_for('static', filename='js/tags.js') }}"></script>

{% with modal_add_tags=ail_tags %}
	{% include 'modals/add_tags.html' %}
{% endwith %}

{% include 'modals/edit_tag.html' %}

<style>
    .object_image {
        filter: blur(5px);
    }
</style>

<div class="card my-1">
	<div class="card-header">
		<h4 class="text-secondary">{{ meta["id"] }} :</h4>
		<ul class="list-group mb-2">
            <li class="list-group-item py-0">
                <table class="table">
                    <tbody style="font-size: 15px;">
                    <tr>
                        <td>
                            <svg height="26" width="26">
                                <g class="nodes">
                                    <circle cx="13" cy="13" r="13" fill="orange"></circle>
                                    <text x="13" y="13" text-anchor="middle" dominant-baseline="central" class="{{ meta["svg_icon"]["style"] }}" font-size="16px">{{ meta["svg_icon"]["icon"] }}</text>
                                </g>
                            </svg>
                            {{ meta['type'] }}
                        </td>
                        <td><b>First Seen:</b> {% if meta['first_seen'] %}{{ meta['first_seen'][0:4] }}-{{ meta['first_seen'][4:6] }}-{{ meta['first_seen'][6:8] }}{% endif %}</td>
                        <td><b>Last Seen:</b> {% if meta['last_seen'] %}{{ meta['last_seen'][0:4] }}-{{ meta['last_seen'][4:6] }}-{{ meta['last_seen'][6:8] }}{% endif %}</td>
                    </tr>
                    </tbody>
                </table>
            </li>
			<li class="list-group-item py-0">
				<div id="accordion_image" class="my-3">
                    <div class="card">
                        <div class="card-header py-1" id="headingImage">
                            <button class="btn w-100 collapsed rotate" data-toggle="collapse" data-target="#collapseImage" aria-expanded="false" aria-controls="collapseImage">
                                <span class="row text-left">
                                    <div class="col-11">
                                        <span class="mt-2">
                                            <i class="far fa-image"></i> Show Image&nbsp;&nbsp;
                                        </span>
                                    </div>
                                    <div class="col-1 text-primary">
                                        <i class="fas fa-chevron-circle-down"></i>
                                    </div>
                                </span>
                            </button>
                        </div>
{#                        <div id="collapseImage" class="collapse show" aria-labelledby="headingImage" data-parent="#accordion_image">#}
{#                            <div class="card-body text-center">#}
{#                                {% include 'objects/image/block_blur_img_slider.html' %}#}
{##}
{#								<img class="object_image mb-1" usemap="#image-map" src="{{ url_for('objects_ocr.ocr_image', filename=meta['id'])}}">#}
{#                                <map name="image-map">#}
{#                                    {% for c in meta['map'] %}#}
{#                                        <area shape="poly" coords="{{ c[0] }}" title="{{ c[1] }}">#}
{#                                    {% endfor %}#}
{#                                </map>#}
{#                            </div>#}
{#                        </div>#}
                    </div>
                </div>
			</li>
            <li class="list-group-item py-0">


            </li>

			<li class="list-group-item py-0">
				<div class="my-2">
					Tags:
					{% for tag in meta['tags'] %}
                        <button class="btn btn-{{ bootstrap_label[loop.index0 % 5] }}"
                                data-toggle="modal" data-target="#edit_tags_modal"
						        data-tagid="{{ tag }}" data-objtype="{{ meta['type'] }}" data-objsubtype="" data-objid="{{ meta["id"] }}">
                                {{ tag }}
						</button>
					{%  endfor %}
					<button type="button" class="btn btn-light" data-toggle="modal" data-target="#add_tags_modal">
                        <i class="far fa-plus-square"></i>
                    </button>
				</div>
			</li>
		</ul>

		{% with obj_type='qrcode', obj_id=meta['id'], obj_subtype='' %}
			{% include 'modals/investigations_register_obj.html' %}
		{% endwith %}
		<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#investigations_register_obj_modal">
			<i class="fas fa-microscope"></i> Investigations
		</button>

        <span class="mb-2 float-right">
            {% if is_correlation %}
                <a href="{{ url_for('objects_qrcode.object_qrcode')}}?id={{ meta['id'] }}">
                    <button class="btn btn-info"><i class="fas fa-expand"></i> Show Object</button>
                </a>
            {% else %}
                <a href="{{ url_for('correlation.show_correlation')}}?type={{ meta['type'] }}&id={{ meta['id'] }}">
                    <button class="btn btn-info"><i class="far fa-eye"></i> Correlations &nbsp;
                    </button>
                </a>
            {% endif %}
        </span>

	</div>
</div>